# SPDX-FileCopyrightText: 2024 SoupGlasses <sofi+git@mailbox.org>
#
# SPDX-License-Identifier: MIT

default_install_hook_types: [pre-commit, pre-push]
repos:
- repo: local
  hooks:
  - id: alejandra
    name: alejandra
    entry: alejandra
    language: system
    files: \.nix$
    stages: [pre-commit]
  - id: deadnix
    name: deadnix
    entry: deadnix --fail
    language: system
    files: \.nix$
    stages: [pre-commit]
  - id: editorconfig-checker
    name: editorconfig-checker
    entry: editorconfig-checker
    language: system
    stages: [pre-commit]
  - id: nix-flake-check
    name: nix flake check
    entry: nix flake check
    language: system
    files: '.*\.(nix|lock)$'
    pass_filenames: false
    stages: [pre-push]
  - id: reuse
    name: reuse
    entry: reuse lint
    language: system
    pass_filenames: false
    stages: [pre-commit]
